using VContainer;
using VContainer.Unity;
using Xianxia.Sect.Visual;

namespace Xianxia.Sect.Installers
{
    /// <summary>
    /// PHASE 1 refactor: บล็อก "Visual system" (Phase 1/2/5/3) ย้ายมาจาก
    /// GameLifetimeScope.Configure() ครบทุกบรรทัด — ค่า config (SpriteSheetEnabled,
    /// SpineActivationRequested, SpineSkeletonResourcePath) ตั้งที่บรรทัดเดิม
    /// พร้อม comment ต้นฉบับ (S4 decision ฯลฯ)
    /// </summary>
    internal static class VisualInstaller
    {
        public static void RegisterVisualSystem(this IContainerBuilder builder)
        {
            // --- Visual system Phase 1 (foundation only — ไม่มี spawn ในฉาก) ---
            // Flags default false ทั้งคู่ (C12) — S4 license ยังไม่ตัดสิน
            builder.RegisterInstance(VisualRuntimeConfig.Instance);
            builder.Register<AppearanceResolver>(Lifetime.Singleton);

            // --- Visual system Phase 2 (SpriteSheet spawn in real scenes) ---
            // C6: SpriteSheetEnabled flips true ONLY after VisualCoverageValidator
            // passes for every roster part (chibi sheets generated by
            // Xianxia/Generate Chibi Placeholder Sheets — Phase 2 T1).
            // SpineEnabled stays FALSE (C1 — S4 license undecided).
            VisualRuntimeConfig.Instance.SpriteSheetEnabled = true;
            builder.Register<ChibiFrameBank>(Lifetime.Singleton);
            builder.RegisterEntryPoint<ChibiFrameClock>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<DiscipleVisualSystem>(Lifetime.Singleton).AsSelf();

            // --- Visual system Phase 5 (entitlement — §8; owner = rank proxy รอ Q1) ---
            // Register เป็นคู่ interface/concrete — SectStateProvider inject interface
            // แล้ว bind-late ผ่าน type-test (ผูกตรงผ่าน DI จะ cycle; concrete Resolve
            // ตรง ๆ ไม่ได้ใน VContainer ตัวนี้ — Register<I,Impl> จดเฉพาะ interface)
            builder.Register<IVisualEntitlementProvider,
                             DefaultEntitlementProvider>(Lifetime.Singleton);

            // --- Visual system Phase 3 (tier policy — §7 render-only allocation) ---
            // S4 LICENSE DECISION (2026-09-25 — confirmed by product owner):
            // Spine Editor + runtime license verified per phase0-results §4 → the gate
            // flips TRUE here at the composition root (the sanctioned human-decision
            // point, same pattern as SpriteSheetEnabled above). VisualSpineBootstrap
            // still owns the actual activation and stays INERT if the rig asset fails
            // to load — this line only records the human decision.
            VisualRuntimeConfig.Instance.SpineActivationRequested = true;
            // Interim shared rig: no chibi_base exists yet — the generic MALE rig stands
            // in for every Spine-allocated disciple WITHOUT a Q5 override (today: only
            // d003). Story characters (d000/d002) always render their own rigs through
            // Resources/Data/visual_overrides.json regardless of this path.
            VisualRuntimeConfig.Instance.SpineSkeletonResourcePath =
                "Avatar/Spine/male/1113103_1";
            // Spine backend activates ONLY inside VisualSpineBootstrap (Visual.Spine
            // assembly, self-activating via [RuntimeInitializeOnLoadMethod]) — it never
            // sets the gate itself. This scope deliberately does NOT reference the
            // Visual.Spine assembly — referencing it would drag spine-unity back into
            // the core compile.
            builder.RegisterInstance(VisualTierPolicy.Instance);
        }
    }
}
