using MessagePipe;
using UnityEngine;
using VContainer;
using VContainer.Unity;
using Xianxia.Sect.Messages;
using Xianxia.Sect.Tests;

namespace Xianxia.Sect
{
    // Composition root for the whole game framework (see the architecture
    // diagram: this is the "Game manager · VContainer composition root" box).
    // Registers the internal MessagePipe bus, the MessagePipe.Interprocess
    // TCP transport to the external MCP bridge process, and the four
    // gameplay subsystems as VContainer entry points.
    public class GameLifetimeScope : LifetimeScope
    {
        /// <summary>
        /// Static access point to this scope's container (Editor verify tools only).
        /// Set in Awake, cleared in OnDestroy — never used by production gameplay code
        /// (those get constructor injection). Kept here instead of reflection so tools
        /// stay reflection-free (C12).
        /// </summary>
        public static IObjectResolver Injector { get; private set; }

        [SerializeField] private string interprocessHost = "127.0.0.1";
        [SerializeField] private int interprocessPort = 3215;

        [Header("UI (Xianxia.UI.MVP Lite)")]
        [SerializeField] private Xianxia.Sect.UI.UIRoot uiRoot;
        [SerializeField] private Xianxia.Sect.UI.UIPanelCatalog uiPanelCatalog;

        protected override void Awake()
        {
            base.Awake();
            Injector = Container;
            DontDestroyOnLoad(gameObject);
        }

        protected override void OnDestroy()
        {
            Injector = null;
            base.OnDestroy();
        }

        protected override void Configure(IContainerBuilder builder)
        {

            // Scene management
            builder.Register<SceneLoader>(Lifetime.Singleton);
            builder.RegisterComponentInHierarchy<AdditiveSceneTest>();
            // Design-time data now sourced from Luban (see DataTables/ at
            // the workspace root and Assets/Scripts/Data/LubanEventPool.cs),
            // not a ScriptableObject dragged into the Inspector - so this is
            // constructed directly rather than serialized.
            builder.RegisterInstance(new LubanEventPool());

            // Avatar part definitions loaded from Resources/Data/avatar_parts.json
            builder.Register<AvatarPartPool>(Lifetime.Singleton);

            // --- Building Phase 1 (grid placement engine — building-system.md) ---
            // Q1 default: defs from Resources/Data/building_defs.json (hand-written,
            // AvatarPartPool pattern); Q3 default: player-only, no interprocess registration
            // BuildingGrid มี ctor (int,int) ไว้ให้ test — VContainer เลือก ctor ที่มี
            // parameters มากที่สุดเสมอ (TypeAnalyzer) แล้วพยายาม resolve System.Int32
            // จึงต้อง pin ขนาดผ่าน factory ที่ composition root แทน:
            // 24×24 centered origin (−12,−12) — logical cell ตรงกับ GridOverlayRenderer
            // (cell (0,0) = กึ่งกลางแบ็คกราว, cell ติดลบได้ทั้งสองแกน)
            builder.Register<Xianxia.Sect.Building.BuildingGrid>(
                resolver => new Xianxia.Sect.Building.BuildingGrid(
                    Xianxia.Sect.Visual.GridOverlayRenderer.GridExtent,
                    Xianxia.Sect.Visual.GridOverlayRenderer.GridExtent,
                    -Xianxia.Sect.Visual.GridOverlayRenderer.GridExtent / 2,
                    -Xianxia.Sect.Visual.GridOverlayRenderer.GridExtent / 2),
                Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Building.BuildingDefPool>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Building.PlacementController>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.UI.BuildingMenuPresenter>(Lifetime.Transient);
            // เจ้าของโหมดวางจริง (persistent) — ปุ่มลอย/BuildMode* message ต้องรอดจาก
            // การปิดเมนู (presenter เป็น Transient ตายพร้อมเมนู จึงถือ flow ไม่ได้)
            builder.RegisterEntryPoint<Xianxia.Sect.UI.BuildingPlacementUISystem>(Lifetime.Singleton).AsSelf();
            // BuildingSystem entry point มีอยู่แล้ว (RegisterEntryPoint<BuildingSystem> ด้านล่าง) — ไม่เพิ่มซ้ำ

            // --- Visual system Phase 1 (foundation only — ไม่มี spawn ในฉาก) ---
            // Flags default false ทั้งคู่ (C12) — S4 license ยังไม่ตัดสิน
            builder.RegisterInstance(Xianxia.Sect.Visual.VisualRuntimeConfig.Instance);
            builder.Register<Xianxia.Sect.Visual.AppearanceResolver>(Lifetime.Singleton);

            // --- Visual system Phase 2 (SpriteSheet spawn in real scenes) ---
            // C6: SpriteSheetEnabled flips true ONLY after VisualCoverageValidator
            // passes for every roster part (chibi sheets generated by
            // Xianxia/Generate Chibi Placeholder Sheets — Phase 2 T1).
            // SpineEnabled stays FALSE (C1 — S4 license undecided).
            Xianxia.Sect.Visual.VisualRuntimeConfig.Instance.SpriteSheetEnabled = true;
            builder.Register<Xianxia.Sect.Visual.ChibiFrameBank>(Lifetime.Singleton);
            builder.RegisterEntryPoint<Xianxia.Sect.Visual.ChibiFrameClock>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<Xianxia.Sect.Visual.DiscipleVisualSystem>(Lifetime.Singleton).AsSelf();

            // --- Visual system Phase 5 (entitlement — §8; owner = rank proxy รอ Q1) ---
            // Register เป็นคู่ interface/concrete — SectStateProvider inject interface
            // แล้ว bind-late ผ่าน type-test (ผูกตรงผ่าน DI จะ cycle; concrete Resolve
            // ตรง ๆ ไม่ได้ใน VContainer ตัวนี้ — Register<I,Impl> จดเฉพาะ interface)
            builder.Register<Xianxia.Sect.Visual.IVisualEntitlementProvider,
                             Xianxia.Sect.Visual.DefaultEntitlementProvider>(Lifetime.Singleton);

            // --- Visual system Phase 3 (tier policy — §7 render-only allocation) ---
            // S4 LICENSE DECISION (2026-09-25 — confirmed by product owner):
            // Spine Editor + runtime license verified per phase0-results §4 → the gate
            // flips TRUE here at the composition root (the sanctioned human-decision
            // point, same pattern as SpriteSheetEnabled above). VisualSpineBootstrap
            // still owns the actual activation and stays INERT if the rig asset fails
            // to load — this line only records the human decision.
            Xianxia.Sect.Visual.VisualRuntimeConfig.Instance.SpineActivationRequested = true;
            // Interim shared rig: no chibi_base exists yet — the generic MALE rig stands
            // in for every Spine-allocated disciple WITHOUT a Q5 override (today: only
            // d003). Story characters (d000/d002) always render their own rigs through
            // Resources/Data/visual_overrides.json regardless of this path.
            Xianxia.Sect.Visual.VisualRuntimeConfig.Instance.SpineSkeletonResourcePath =
                "Avatar/Spine/male/1113103_1";
            // Spine backend activates ONLY inside VisualSpineBootstrap (Visual.Spine
            // assembly, self-activating via [RuntimeInitializeOnLoadMethod]) — it never
            // sets the gate itself. This scope deliberately does NOT reference the
            // Visual.Spine assembly — referencing it would drag spine-unity back into
            // the core compile.
            builder.RegisterInstance(Xianxia.Sect.Visual.VisualTierPolicy.Instance);

            // --- UI (Xianxia.UI.MVP Lite) ---
            // SectHudView is gone - replaced by the WalletHud panel below,
            // which gets its data from SectResourceChangedMessage instead of
            // polling ISectStateProvider on a timer.
            builder.RegisterInstance(uiRoot);
            builder.RegisterInstance(uiPanelCatalog);
            builder.Register<Xianxia.Sect.UI.UIService>(Lifetime.Singleton);
            builder.Register<DecisionExecutor>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.UI.EventPopupPresenter>(Lifetime.Transient);
            builder.Register<Xianxia.Sect.UI.WalletHudPresenter>(Lifetime.Transient);
            builder.Register<Xianxia.Sect.UI.LogWindowPresenter>(Lifetime.Transient);
            builder.Register<Xianxia.Sect.UI.AvatarCustomizationPresenter>(Lifetime.Transient);
            builder.Register<Xianxia.Sect.Visual.TaskActivityMapper>(Lifetime.Singleton); // Phase 4: CurrentTask→activity (data-driven)
            builder.Register<Xianxia.Sect.UI.DiscipleDetailPresenter>(Lifetime.Transient); // Phase 4: click chibi → detail
            builder.Register<Xianxia.Sect.UI.BottomMenuPresenter>(Lifetime.Transient); // persistent bottom bar (สร้าง / ศิษย์)
            builder.Register<Xianxia.Sect.UI.ResourcePopupPresenter>(Lifetime.Transient); // คลังสินค้า popup (read-only stockpile)
            builder.Register<Xianxia.Sect.UI.DiscipleListPresenter>(Lifetime.Transient); // รายชื่อศิษย์ (cards + baked icons)
            builder.RegisterEntryPoint<Xianxia.Sect.UI.DiscipleDetailUISystem>(Lifetime.Singleton); // Phase 4: message → panel
            builder.RegisterEntryPoint<Xianxia.Sect.UI.WorldEventUISystem>(Lifetime.Singleton);
            builder.RegisterEntryPoint<Xianxia.Sect.UI.UIBootstrap>(Lifetime.Singleton);

            // --- in-memory pub/sub + request-response (internal subsystem bus) ---
            var options = builder.RegisterMessagePipe(pipeOptions =>
            {
                pipeOptions.InstanceLifetime = InstanceLifetime.Singleton;
            });

            // --- interprocess transport: Unity <-> MCP bridge process, over TCP ---
            // Unity hosts the TCP endpoint; the bridge process connects as a client.
            var messagePipeBuilder = builder.ToMessagePipeBuilder();
            var interprocess = messagePipeBuilder.AddTcpInterprocess(
                interprocessHost,
                interprocessPort,
                tcpOptions =>
                {
                    tcpOptions.HostAsServer = true;
                    tcpOptions.InstanceLifetime = InstanceLifetime.Singleton;
                });

            // Only register the message types the bridge actually needs on the
            // wire. TimeSpeedChangedMessage stays internal-only on purpose -
            // the bridge doesn't need per-frame speed changes.
            // WorldEventTriggeredMessage is deliberately NOT registered here
            // (see AwaitWorldEventRequest in GameMessages.cs) - the bridge
            // can't safely IDistributedSubscriber over this TCP transport,
            // it's request-response only for that one.
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, DiscipleRecruitedMessage>(interprocess);
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, DiscipleRankChangedMessage>(interprocess);
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, SectResourceChangedMessage>(interprocess);
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, ContributionEarnedMessage>(interprocess);
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, ExecuteDecisionMessage>(interprocess);

            // Request/response: bridge asks "what's the sect state right now".
            // Correction from an earlier pass: RegisterTcpRemoteRequestHandler
            // is needed here too, even though Unity is HostAsServer=true and
            // holds the real handler. It's what wires the TCP worker to the
            // registered IAsyncRequestHandler, not just a caller-side proxy -
            // confirmed against Wanxiang.Guanxiangtai's FrontendIpcServer.cs,
            // which registers both on its (HostAsServer=true) side.
            messagePipeBuilder.RegisterTcpRemoteRequestHandler<SectStateQuery, SectStateSnapshot>(interprocess);
            builder.RegisterAsyncRequestHandler<SectStateQuery, SectStateSnapshot, SectStateQueryHandler>(options);

            // Request/response: bridge asks "wait for the next world event"
            // and blocks until Unity's TimeSystem completes it - see the
            // comment on AwaitWorldEventRequest for why this isn't pub/sub.
            messagePipeBuilder.RegisterTcpRemoteRequestHandler<AwaitWorldEventRequest, AwaitWorldEventResponse>(interprocess);
            builder.RegisterAsyncRequestHandler<AwaitWorldEventRequest, AwaitWorldEventResponse, AwaitWorldEventHandler>(options);

            // Request/response: a disciple buying an item from the sect
            // stockpile with contribution.
            messagePipeBuilder.RegisterTcpRemoteRequestHandler<PurchaseItemRequest, PurchaseItemResponse>(interprocess);
            builder.RegisterAsyncRequestHandler<PurchaseItemRequest, PurchaseItemResponse, PurchaseItemHandler>(options);

            // Request/response: changing a disciple's avatar part
            messagePipeBuilder.RegisterTcpRemoteRequestHandler<ChangeAvatarPartRequest, ChangeAvatarPartResponse>(interprocess);
            builder.RegisterAsyncRequestHandler<ChangeAvatarPartRequest, ChangeAvatarPartResponse, ChangeAvatarPartHandler>(options);

            // Interprocess pub/sub: broadcast avatar equipment changes to UI + MCP client
            messagePipeBuilder.RegisterTcpInterprocessMessageBroker<string, AvatarEquipmentChangedMessage>(interprocess);

            // --- camera rig ports (test seams; see CameraRigPorts.cs) ---
            // The rig talks to the bus/scene/Resources/Time only through these
            // interfaces, so EditMode tests can drive it with fakes.
            builder.Register<Xianxia.Sect.Visual.IRigMessageBus, Xianxia.Sect.Visual.MessagePipeRigBus>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Visual.ICameraRigEnvironment, Xianxia.Sect.Visual.SceneEnvironment>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Visual.ICellSpriteMetrics, Xianxia.Sect.Visual.ResourcesCellSpriteMetrics>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Visual.IMainThreadQueue, Xianxia.Sect.Visual.UniTaskMainThreadQueue>(Lifetime.Singleton);
            builder.Register<Xianxia.Sect.Visual.IRigClock, Xianxia.Sect.Visual.UnityRigClock>(Lifetime.Singleton);
            // pan input (คลิกขวาค้าง+ลาก) — ผูกกับ Unity Input เฉพาะ play mode ผ่าน
            // CameraRigPanBootstrap ([RuntimeInitializeOnLoadMethod]); EditMode test
            // ไม่มี wire → CameraRigController ข้าม input ทั้งหมด (test-safe)

            // --- gameplay subsystems, started/ticked by VContainer ---
            builder.RegisterEntryPoint<TimeSystem>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<DiscipleSystem>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<ResourceCraftingSystem>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<BuildingSystem>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<Xianxia.Sect.Visual.CameraRigController>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<Xianxia.Sect.Visual.GridOverlayRenderer>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<Xianxia.Sect.Visual.TerrainBackdropRenderer>(Lifetime.Singleton).AsSelf();

            // Camera framing: plain-C# config (task forbids ScriptableObject
            // here); sprite/PPU/grid values are measured at runtime.
            builder.Register<Xianxia.Sect.Visual.CameraFramingConfig>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<DecisionLogger>(Lifetime.Singleton).AsSelf();
            builder.RegisterEntryPoint<WorldEventSystem>(Lifetime.Singleton).AsSelf();

            // Aggregates the subsystems above into one SectEconomyState for
            // SectStateQueryHandler to serve. See ISectStateProvider.
            builder.Register<ISectStateProvider, SectStateProvider>(Lifetime.Singleton);
        }
    }
}
