using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Xianxia.Sect.UI
{
    // View-layer DTO, deliberately separate from Messages.EventChoiceInfo
    // (the wire type) - same split reasoning as EventData/EventChoiceOption
    // vs EventChoiceInfo from the Luban migration.
    public class EventChoiceViewData
    {
        public string ChoiceId;
        public string Label;
    }

    /// <summary>
    /// E3 — the world-event popup. The view only renders what the presenter tells
    /// it; the decision itself always goes through DecisionExecutor (single path).
    ///
    /// Layout comes from the prefab (generated by EventPopupPanelGenerator):
    /// a full-canvas root carrying the light, non-click-blocking dim, with one
    /// fixed-size framed panel child. No ContentSizeFitter anywhere — the panel
    /// must not resize itself under the player.
    /// </summary>
    public class EventPopupView : UIViewBase
    {
        /// <summary>Shown when the event was resolved elsewhere (e.g. the AI GM) while the popup was open.</summary>
        public const string ResolvedElsewhereText = "ตัดสินใจแล้วจากที่อื่น";

        [SerializeField] private TMP_Text titleText;
        [SerializeField] private TMP_Text descriptionText;
        [SerializeField] private TMP_Text statusText;
        [SerializeField] private Transform choicesRoot;
        [SerializeField] private Button choiceButtonPrefab;
        [SerializeField] private Button hideButton;

        /// <summary>A visible choice button was pressed (carries the choice id).</summary>
        public event Action<string> ChoiceClicked;
        /// <summary>The player asked to hide the popup ("ซ่อน" or Escape). Never a decision.</summary>
        public event Action HideRequested;
        /// <summary>The "resolved elsewhere" note finished its few seconds on screen.</summary>
        public event Action ResolvedNoteFinished;

        private sealed class SpawnedChoice
        {
            public string ChoiceId;
            public Button Button;
        }

        private readonly List<SpawnedChoice> _spawned = new List<SpawnedChoice>();
        private float _resolvedNoteRemaining;

        /// <summary>
        /// Root stays full-canvas so the dim covers the screen and the framed panel
        /// keeps its own fixed size. Any ContentSizeFitter left on a stale prefab is
        /// neutralised rather than destroyed (Destroy is unavailable in EditMode
        /// tests, and a fitter here would resize the panel while text changes).
        /// </summary>
        public override void ApplyDefaultLayout()
        {
            var rt = transform as RectTransform;
            if (rt != null)
            {
                rt.anchorMin = Vector2.zero;
                rt.anchorMax = Vector2.one;
                rt.offsetMin = Vector2.zero;
                rt.offsetMax = Vector2.zero;
            }

            var csf = GetComponent<ContentSizeFitter>();
            if (csf != null)
            {
                csf.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;
                csf.verticalFit = ContentSizeFitter.FitMode.Unconstrained;
            }
        }

        public override void Show()
        {
            WireHideButton();
            gameObject.SetActive(true);
        }

        public override void Hide()
        {
            base.Hide();
            ClearChoices(); // don't leak stale choice buttons into the next event
            _resolvedNoteRemaining = 0f;
        }

        public void SetEvent(string eventId, string description)
        {
            if (titleText != null) titleText.text = eventId;
            if (descriptionText != null) descriptionText.text = description;
        }

        public void SetChoices(List<EventChoiceViewData> choices)
        {
            ClearChoices();

            if (choicesRoot == null || choiceButtonPrefab == null) return;

            foreach (var choice in choices)
            {
                var button = Instantiate(choiceButtonPrefab, choicesRoot);

                // The prefab carries the button as an INACTIVE template (that is how
                // the file stores it) - Instantiate keeps activeSelf, so an
                // un-activated clone would be invisible and unclickable.
                button.gameObject.SetActive(true);

                // A Button with no target graphic renders nothing and tints nothing.
                if (button.targetGraphic == null)
                {
                    button.targetGraphic = button.GetComponent<Image>();
                }

                var label = button.GetComponentInChildren<TMP_Text>();
                if (label != null) label.text = choice.Label;

                button.interactable = true;

                var choiceId = choice.ChoiceId; // capture for the closure below
                button.onClick.AddListener(() => ChoiceClicked?.Invoke(choiceId));

                _spawned.Add(new SpawnedChoice { ChoiceId = choiceId, Button = button });
            }
        }

        /// <summary>Disables every choice while a decision is being processed.</summary>
        public void SetChoicesEnabled(bool enabled)
        {
            for (int i = 0; i < _spawned.Count; i++)
            {
                if (_spawned[i].Button != null) _spawned[i].Button.interactable = enabled;
            }
        }

        /// <summary>Inline message (a rejection reason, or the event id awaiting a decision).</summary>
        public void SetStatus(string message)
        {
            if (statusText == null) return;
            statusText.text = message ?? string.Empty;
        }

        public void ClearStatus() => SetStatus(string.Empty);

        /// <summary>
        /// The event was resolved elsewhere while the popup was open: lock the choices,
        /// say so for a few seconds, then close (the presenter is told on
        /// <see cref="ResolvedNoteFinished"/> so its opener stays in sync).
        /// </summary>
        public void ShowResolvedElsewhereNote(float seconds)
        {
            _resolvedNoteRemaining = Mathf.Max(0f, seconds);
            SetChoicesEnabled(false);
            SetStatus(ResolvedElsewhereText);
        }

        private void Update()
        {
            Tick(Time.unscaledDeltaTime);

            if (Input.GetKeyDown(KeyCode.Escape) && !IsTextInputFocused()) PressEscape();
        }

        // E3 (modal interplay, kept from before): while another blocking modal is
        // open the popup yields to it instead of being forced over it — the chip
        // (WorldEventChipPresenter) is what signals "an event is still waiting"
        // in that state, and the popup comes back by itself once the modal closes.
        private CanvasGroup modalVisibility;
        private void LateUpdate()
        {
            if (modalVisibility == null)
            {
                modalVisibility = GetComponent<CanvasGroup>();
                if (modalVisibility == null) modalVisibility = gameObject.AddComponent<CanvasGroup>();
            }
            bool visible = !DiscipleModalScope.IsOpen;
            modalVisibility.alpha = visible ? 1 : 0;
            modalVisibility.blocksRaycasts = visible;
            modalVisibility.interactable = visible;
        }

        /// <summary>Timer step, split out so EditMode tests can drive it without a frame.</summary>
        public void Tick(float deltaSeconds)
        {
            if (_resolvedNoteRemaining <= 0f) return;

            _resolvedNoteRemaining -= deltaSeconds;
            if (_resolvedNoteRemaining > 0f) return;

            _resolvedNoteRemaining = 0f;
            Hide();
            ResolvedNoteFinished?.Invoke();
        }

        private void PressEscape()
        {
            if (!isActiveAndEnabled) return;
            HideRequested?.Invoke();
        }

        /// <summary>
        /// Legacy Input Manager (the project's existing convention — DiscipleListView,
        /// TimeControlView): Escape never fires while a text input has focus.
        /// </summary>
        private static bool IsTextInputFocused()
        {
            var es = EventSystem.current;
            var go = es != null ? es.currentSelectedGameObject : null;
            if (go == null) return false;
            return go.GetComponent<TMP_InputField>() != null
                || go.GetComponentInParent<TMP_InputField>() != null;
        }

        private bool _hideWired;

        private void WireHideButton()
        {
            if (_hideWired || hideButton == null) return;
            hideButton.onClick.AddListener(OnHideButton);
            _hideWired = true;
        }

        private void OnHideButton() => HideRequested?.Invoke();

        private void OnDestroy()
        {
            if (hideButton != null && _hideWired) hideButton.onClick.RemoveListener(OnHideButton);
            _hideWired = false;
            ChoiceClicked = null;
            HideRequested = null;
            ResolvedNoteFinished = null;
        }

        private void ClearChoices()
        {
            for (int i = 0; i < _spawned.Count; i++)
            {
                var button = _spawned[i].Button;
                // DestroyImmediate — this panel is rebuilt in EditMode tests too,
                // where the deferred Destroy logs "Destroy may not be called from
                // edit mode" (same reason as TaskAssignmentView.ClearRows).
                if (button != null) DestroyImmediate(button.gameObject);
            }
            _spawned.Clear();
        }

        // ---- test accessors (EditMode tests, no reflection — C12) ----

        public bool VisibleForTest => gameObject.activeSelf;
        public string TitleForTest => titleText != null ? titleText.text : null;
        public string DescriptionForTest => descriptionText != null ? descriptionText.text : null;
        public string StatusForTest => statusText != null ? statusText.text : null;
        public bool IsShowingResolvedNoteForTest => _resolvedNoteRemaining > 0f;
        public int ChoiceCountForTest => _spawned.Count;

        public string ChoiceIdAtForTest(int index) =>
            index >= 0 && index < _spawned.Count ? _spawned[index].ChoiceId : null;

        public bool IsChoiceInteractableForTest(string choiceId)
        {
            for (int i = 0; i < _spawned.Count; i++)
            {
                if (_spawned[i].ChoiceId == choiceId) return _spawned[i].Button != null && _spawned[i].Button.interactable;
            }
            return false;
        }

        /// <summary>Drives the real button's onClick, so tests exercise the production click path.</summary>
        public void InvokeChoiceForTest(string choiceId)
        {
            for (int i = 0; i < _spawned.Count; i++)
            {
                if (_spawned[i].ChoiceId != choiceId) continue;
                if (_spawned[i].Button != null) _spawned[i].Button.onClick.Invoke();
                return;
            }
            Debug.LogWarning($"[EventPopupView] InvokeChoiceForTest: no spawned choice '{choiceId}'");
        }

        public void InvokeHideForTest() => OnHideButton();
        public void PressEscapeForTest() => PressEscape();
        public void AdvanceForTest(float deltaSeconds) => Tick(deltaSeconds);
    }
}
