// <auto-generated>
//   Generated by Tools/art/bake_land_mask.py - do not edit by hand.
//   Regenerate after the terrain art changes:  python Tools/art/bake_land_mask.py
//
//   Per-cell "land" mask of the painted backdrop
//   Assets/Resources/tilemap/map/mountain1_wx/mountain1.png (4096x3328 px @ PPU 100 = 40.96x33.28 world
//   units, centred on the origin).
//
//   Land = the flat warm beige ground (rgb 222,214,200) of the plateau tops.
//   Fog banks, rock, trees, the beige plane *outside* the islands and everything
//   off-image are NOT land, so both the build-mode overlay and BuildingGrid.CanPlace
//   stay on the islands instead of spilling over the fog.
//
//   Two filters, both checked against the artist's cross-outs on the preview:
//     * "on an island" - the beige is labelled with 8-connectivity and only the
//       components that do NOT touch the image border are kept (the outer plane is
//       one huge border-touching component).
//     * "worth building on" - the cell mask is labelled again and a region is kept
//       only if it can host the largest footprint in the game, 3x3 cells
//       (pill_hall in building_defs.json). Slivers hanging over a canyon and single
//       cells floating in the mist are dropped with it.
//
//   Cell size / mapping mirror CameraFramingConfig + IsometricCellMath:
//     centre(x,z) = ((x - z) * 1.28/2, (x + z) * 0.66/2)
// </auto-generated>
namespace Xianxia.Sect.Building
{
    /// <summary>
    /// Baked placeable-land mask - 328 of 2500 cells are land.
    /// Row index = z - <see cref="OriginY"/>, column index = x - <see cref="OriginX"/>.
    /// The rect matches GridOverlayRenderer.GridExtent and the production BuildingGrid.
    /// </summary>
    public static class PlaceableLandMask
    {
        public const string SourceImage = "Assets/Resources/tilemap/map/mountain1_wx/mountain1.png";

        /// <summary>Logical cell of Rows[0][0] (matches the isometric cell grid).</summary>
        public const int OriginX = -25;
        public const int OriginY = -25;

        public const int Width = 50;
        public const int Height = 50;

        public const char LandChar = '#';

        /// <summary>Number of land cells in the whole mask.</summary>
        public const int LandCellCount = 328;

        /// <summary>
        /// Largest building footprint the bake required a land region to fit
        /// (pill_hall in building_defs.json). Kept in sync by the generator.
        /// </summary>
        public const int MinFootprintWidth = 3;
        public const int MinFootprintHeight = 3;

        private static readonly string[] Rows =
        {
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................#.......#######.................",
            "...............####.....#########.................",
            ".............##.###....###########................",
            ".............#######...####.#####.................",
            ".............###.####..#########..................",
            "............#.#######..########...................",
            "............#########..#########..................",
            "............##.#####...#########..................",
            ".............#######...##.######..................",
            "..............##..##..###########.................",
            "..............######..####.######.................",
            "..............####.##..###########................",
            "..............######....#.##.####.................",
            "..............#####......#......#.................",
            "...............###.............................#..",
            "..............................................####",
            ".............................................#####",
            "..............................................####",
            "..............................................###.",
            "..................................................",
            "..................####.........##.................",
            ".................#####.........######..#..........",
            ".................#####........###########.........",
            ".................#######.....############.........",
            ".................#######.....#############........",
            "..................####.......#############........",
            "..............................###########.........",
            "..............................#####...............",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
            "..................................................",
        };

        /// <summary>Cell is plateau top surface (mist / rock / tree / off-image = false).</summary>
        public static bool IsLand(int x, int z)
        {
            int ix = x - OriginX;
            int iz = z - OriginY;
            if (ix < 0 || iz < 0 || ix >= Width || iz >= Height) return false;
            return Rows[iz][ix] == LandChar;
        }

        /// <summary>
        /// Row-major (index = (z - originZ) * width + (x - originX)) bool block for
        /// an arbitrary rect of logical cells - the shape BuildingGrid.SetPlaceableMask
        /// takes. Cells outside the mask bounds are false (fail-closed).
        /// </summary>
        public static bool[] BuildCells(int originX, int originZ, int width, int height)
        {
            var cells = new bool[width * height];
            for (int iz = 0; iz < height; iz++)
            {
                for (int ix = 0; ix < width; ix++)
                {
                    cells[iz * width + ix] = IsLand(originX + ix, originZ + iz);
                }
            }
            return cells;
        }
    }
}
